// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sirupsen/logrus"
	"go-gin-mall/internal/config"
	"go-gin-mall/internal/domain/user"
	"go-gin-mall/internal/driving/repository"
	"go-gin-mall/internal/handler"
)

// Injectors from wire.go:

func wireUserHandler(c config.DBConf, logger *logrus.Logger) *handler.UserHandler {
	userRepository := repository.NewUserRepository()
	userDomainService := user.NewUserDomainService(logger, userRepository)
	userHandler := handler.NewUserHandler(logger, userDomainService)
	return userHandler
}
